export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_RECIPES_PENDING = 'REQUEST_RECIPES_PENDING';
export const REQUEST_RECIPES_SUCCESS = 'REQUEST_RECIPES_SUCCESS';
export const REQUEST_RECIPES_FAILED = 'REQUEST_RECIPES_FAILED';
